# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a1ee4f793f583dbb32721c6928dc47a372c9e7d7883a4fed55e7e24905a6cab10b2a44a72561f4b80570303aad620479ea4f2d46b5e55251a95a6c651341461

test:
  secret_key_base: e2b0f9c97c64ec192b84a68fb51ad1515ac5f73dd318f6aa8bb87637a8f2ee6a2efef3d48597d2407b592b08202907f0f3a324f7384a28c8f2c4c4a6c496f65b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
